GRANT ALL ON XXDBD.xxdbd_learn_user TO HRRO;

GRANT ALL ON XXDBD.xxdbd_learn_sup_accounts TO HRRO;

GRANT ALL ON XXDBD.xxdbd_learn_supervisees TO HRRO;

GRANT ALL ON XXDBD.XXDBD_LEARN_CUSTOM_FIELDS TO HRRO;

GRANT ALL ON xxdbd.xxdbd_learn_custom_field_val TO HRRO;

GRANT ALL ON XXDBD.XXDBD_FSN_LEARN_STG_TBL  TO HRRO;

GRANT ALL ON XXDBD.XXDBD_GL_R12HR_DNA_RUN_LOG  TO HRRO;

/