WHENEVER SQLERROR CONTINUE

drop table XXDBD.XXDBD_FSN_LEARN_STG_TBL;

CREATE TABLE XXDBD.XXDBD_FSN_LEARN_STG_TBL
(
  ORACLE_ID                 VARCHAR2(1000 BYTE),
  FIRST_NAME                VARCHAR2(1000 BYTE),
  LAST_NAME                 VARCHAR2(1000 BYTE),
  MIDDLE_INITIAL            VARCHAR2(1000 BYTE),
  TITLE                     VARCHAR2(1000 BYTE),
  LOCATION                  VARCHAR2(1000 BYTE),
  ORGANIZATION              VARCHAR2(1000 BYTE),
  EMPLOYEE_TYPE             VARCHAR2(1000 BYTE),
  HOME_CITY                 VARCHAR2(1000 BYTE),
  HOME_STATE                VARCHAR2(1000 BYTE),
  HOME_ZIP                  VARCHAR2(1000 BYTE),
  HOME_COUNTRY              VARCHAR2(1000 BYTE),
  EMAIL                     VARCHAR2(1000 BYTE),
  SUPERVISOR_ID             VARCHAR2(1000 BYTE),
  COST_CENTER               VARCHAR2(1000 BYTE),
  JOB_STATE                 VARCHAR2(1000 BYTE),
  PT_FT                     VARCHAR2(1000 BYTE),
  DIEBOLD_MASTER            VARCHAR2(1000 BYTE),
  LANGUAGE                  VARCHAR2(1000 BYTE),
  JOB_GROUP                 VARCHAR2(1000 BYTE),
  HR_PARTNER_ID             VARCHAR2(1000 BYTE),
  LATEST_START_DATE         VARCHAR2(1000 BYTE),
  ALTERNATE_TITLE           VARCHAR2(1000 BYTE),
  GRADE                     VARCHAR2(1000 BYTE),
  GENDER                    VARCHAR2(1000 BYTE),
  REGION                    VARCHAR2(1000 BYTE),
  HR_PARTNER_NAME           VARCHAR2(1000 BYTE),
  LEARNING_MENTOR_ID        VARCHAR2(1000 BYTE),
  LEARNING_MENTOR_NAME      VARCHAR2(1000 BYTE),
  MATRIX_MANAGER_ID         VARCHAR2(1000 BYTE),
  MATRIX_MANAGER_NAME       VARCHAR2(1000 BYTE),
  VEHICLE                   VARCHAR2(1000 BYTE),
  TECHNICIAN_TYPE           VARCHAR2(1000 BYTE),
  LC_ADMIN                  VARCHAR2(1000 BYTE),
  BRANCH                    VARCHAR2(1000 BYTE),
  ACQUISITION               VARCHAR2(1000 BYTE),
  PRIOR_SUPERVISOR_ID       VARCHAR2(1000 BYTE),
  SYSTEM_ACCESS_SUSPENSION  VARCHAR2(1000 BYTE),
  ORACLE                    VARCHAR2(1000 BYTE),
  SAP                       VARCHAR2(1000 BYTE),
  TBD3                      VARCHAR2(1000 BYTE),
  TBD4                      VARCHAR2(1000 BYTE),
  TBD5                      VARCHAR2(1000 BYTE),
  TBD6                      VARCHAR2(1000 BYTE),
  TBD7                      VARCHAR2(1000 BYTE),
  TBD8                      VARCHAR2(1000 BYTE),
  TBD9                      VARCHAR2(1000 BYTE),
  TBD10                     VARCHAR2(1000 BYTE),
  TBD11                     VARCHAR2(1000 BYTE),
  TBD12                     VARCHAR2(1000 BYTE),
  TBD13                     VARCHAR2(1000 BYTE),
  TBD14                     VARCHAR2(1000 BYTE),
  TBD15                     VARCHAR2(1000 BYTE),
  TEST                      VARCHAR2(1000 BYTE),
  GIN_NUMBER                VARCHAR2(1000 BYTE),
  BUSINESS_GROUP_NAME       VARCHAR2(1000 BYTE),
  SYSTEM_STATUS             VARCHAR2(1000 BYTE),
  LINE_OF_BUSINESS          VARCHAR2(1000 BYTE),
  FUNCTION                  VARCHAR2(1000 BYTE),
  SUB_FUNCTION              VARCHAR2(1000 BYTE),
  DEPARTMENT                VARCHAR2(1000 BYTE),
  SUB_DEPARTMENT            VARCHAR2(1000 BYTE),
  ADP_PERSON_TYPE           VARCHAR2(1000 BYTE),
  ALL_USERS_GROUP_FLAG      VARCHAR2(30 BYTE),
  SUPERVISORS_GROUP_FLAG    VARCHAR2(30 BYTE),
  NEW_HIRES_GROUP_FLAG      VARCHAR2(30 BYTE)
);

drop synonym XXDBD_FSN_LEARN_STG_TBL;

create synonym XXDBD_FSN_LEARN_STG_TBL for xxdbd.XXDBD_FSN_LEARN_STG_TBL;

create index XXDBD_FSN_LEARN_STG_TBL_PK on xxdbd.XXDBD_FSN_LEARN_STG_TBL(ORACLE_ID)

create index xxdbd.XXDBD_FSN_LEARN_STG_TBL_NQ1 on xxdbd.XXDBD_FSN_LEARN_STG_TBL(supervisor_id);

create index xxdbd.XXDBD_FSN_LEARN_STG_TBL_NQ2 on xxdbd.XXDBD_FSN_LEARN_STG_TBL(hr_partner_id);

create index xxdbd.XXDBD_FSN_LEARN_STG_TBL_NQ3 on xxdbd.XXDBD_FSN_LEARN_STG_TBL(learning_mentor_id);

create index xxdbd.XXDBD_FSN_LEARN_STG_TBL_NQ4 on xxdbd.XXDBD_FSN_LEARN_STG_TBL(matrix_manager_id);